# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e112ecba330f88d41cb3b88ea188c8273dff101015ddf85d0e51a399c1543a68ed9062b58f1b18bcbf0af12ba0b57582290f9f7c3be9dbc33919a95611f026c8

test:
  secret_key_base: f5386d7223b4a5045ce4304a064350ec8105c5651932ebae9923ae875a184f557edbf765f204e3d52ea68f8f29700d964a92b1916a906148e7392b70a2d309c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
